name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Environment Check 
      run: env

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential g++-17

    - name: Install Eigen
      run: |
        wget https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz
        tar -xvf eigen-3.4.0.tar.gz
        cd eigen-3.4.0
        mkdir build
        cd build
        cmake ..
        make
        sudo make install
    
    - name: Install lazycsv.hpp
      run: |
        cd ../..
        mkdir externals
        cd externals
        git clone https://github.com/ashtum/lazycsv.git
        cp lazycsv/include/lazycsv.hpp .
        

    - name: Setup GoogleTest
      uses: Bacondish2023/setup-googletest@v1
      with:
        tag: v1.14.0

    - name: Build main application
      run: |
        chmod +x build.sh
        ./build.sh

    - name: Run C++ tests
      run: |
        ./build.sh test
        ./tests  # Ensure this matches your test binary path